services:
  git-mirror:
    image: espressif/git-mirror:1
    ports:
      - "6688:6688"
    command: ["/config/config.toml"]
    volumes:
      - /opt/git-mirror/data:/data
      - /opt/git-mirror/config:/config
    restart: always
